### ISSUE TITLE
Rename extension, update assets & documentation 

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-platform-7-custom-batch#47]
Hi Patrick and Jan,

I hope today finds you well! This issue is being opened to ask if you would be open to renaming your extension on GitHub to reference Camunda Platform 7 rather than Camunda BPM after its release on April 12th, 2022. (For example: camunda-platform-7-graphql) This change will also likely impact any screenshots you have in the README that reference Camunda BPM or previous versions of Camunda Platform, and this will likely need to also be updated throughout the repo's documentation as a whole. You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with. 

While it is not a **requirement** that you rename your extension to align with Camunda Platform 7, we would **greatly** appreciate it if you could make these changes, and merge them anytime after April 12th, 2022.

 if you have any questions or require any assistance, please do not hesitate to reach out to @camunda-community-hub/devrel! :)

**Comment by akeller** [comment]
I went to add `![Compatible with: Camunda Platform 7](https://img.shields.io/badge/Compatible%20with-Camunda%20Platform%207-26d07c)` but didn't quite understand the structure in the README. 

@jangalinski @pschalk please update this project when you get a chance. Thanks!

**Comment by akeller** [comment]
@camunda-community-hub/devrel looking for assistance here

**Comment by akeller** [comment]
@pschalk what would you like the repo name to be? `camunda-platform-7-custom-batch`?

**Comment by pschalk** [comment]
Yes, to "camunda-platform-7-custom-batch"

**Comment by berndruecker** [comment]
I renamed the repo but still need to check the build problem - not sure if I will find the time this week - but I will try

**Comment by berndruecker** [comment]
Fixed by https://github.com/camunda-community-hub/camunda-platform-7-custom-batch/commit/bcb17a15593a8dca815be9841ce1efcac2ce80b5 - build is working now

**Comment by berndruecker** [comment]
@pschalk I just assumed this issue is closed now - feel free to reopen if not true (then: sorry ;-))

**Comment by pschalk** [comment]
@berndruecker hm, do you know why the artifacts get not pushed into the mvn central artifactory like in the past? 
=> https://mvnrepository.com/search?q=org.camunda.community.batch

Thy just appear in the camunda jfrog artifactory: 
=> https://artifacts.camunda.com/ui/packages/gav:%2F%2Forg.camunda.community.batch:camunda-platform-7-custom-batch-core/1.6.0?name=camunda-platform-7-custom-batch-core&type=packages&activeTab=builds

**Comment by berndruecker** [comment]
Hi @pschalk: I did release it yesterday and it looks OK in the Sonatype Nexus. So I guess this is a timing issue and we need to wait a bit for the artifact to be discoverable...

**Comment by pschalk** [comment]
Your right, now it's there. :)
