### ISSUE TITLE
Version 1.18.0 is not available in Maven central

### ISSUE THREAD

**Issue by rohwerj** [camunda-community-hub/camunda-platform-7-custom-batch#54]
The newest version that is compatible with Camunda 7.18 (1.18.0) is not available on Maven central.

**Comment by pschalk** [comment]
@Rin can you please help? 
Found an old issue where you had to manually release the new version? (https://github.com/camunda-community-hub/camunda-platform-7-custom-batch/issues/38)

**Comment by zambrovski** [comment]
@camunda-community-hub/devex could youe please check?

**Comment by akeller** [comment]
@camunda-community-hub/devrel should be able to assist here.

**Comment by xomiamoore** [comment]
Hello! Taking a look at this now :)

**Comment by rohwerj** [comment]
@xomiamoore What is the status of this issue? Are there any problems with the release?

**Comment by berndruecker** [comment]
This is wired: I can see the release/deploy on the Github action, but don't find an artifact on staging in Sonatype - also not deployed: https://oss.sonatype.org/#nexus-search;quick~camunda-platform-7-custom-batch-

@rohwerj Would it be OK if I release another 1.18.1 to check if that ends up on Sonatype's server as expected?

**Comment by rohwerj** [comment]
@berndruecker For me this would be totally okay, but I think @pschalk or @zambrovski have to say, if there is a reason not to do it

**Comment by pschalk** [comment]
@berndruecker for me it's ok, thanks!

**Comment by berndruecker** [comment]
@rohwerj @pschalk Released 1.18.1 and directly released it from Sonatype. Should be on central soon. Sorry, for the inconvenience!
